### ISSUE TITLE
Remove restrictions on Dependabot GitHub Actions update

### ISSUE THREAD

**Issue by matthewfeickert** [madminer-tool/madminer#514]
There is a discussion under https://github.com/madminer-tool/madminer/pull/509#discussion_r954036008 about if the current restrictions on Dependabot updates for GitHub Actions should be loosened. At the moment the current settings

https://github.com/madminer-tool/madminer/blob/03cd67b4c6c1435ef0de6798c824fc4692341ab7/.github/dependabot.yml#L5-L12

allow only one action

https://github.com/madminer-tool/madminer/blob/03cd67b4c6c1435ef0de6798c824fc4692341ab7/.github/workflows/publish.yml#L42

can ever be updated by Dependabot.

At the moment the restrictions invalidate the usefulness of the updater. There is no practical argument to keep them in my mind as GitHub Actions already do not make any promise of true SemVer and [most of Scikit-HEP uses the updater](https://scikit-hep.org/developer/gha_basic#updating) with no negative consequences.

**Comment by Sinclert** [comment]
I already expressed my concerns about turning on GHA Actions major releases auto-creation of PRs.

Given the number of repositories some of us have Dependabot PRs turned on, we prefer to keep their automatic creation to those we can **immediately act on** (following SerVer best intent: minor and patch bumping ones). Therefore, avoiding been notified about every major release through a PR requiring us to perform some `CHANGELOG` investigation. People may prefer to deal with those in a manual fashion, whenever they have the bandwidth. This is the way I prefer too.

As a last point: Dependabot should not be used as a _notification system_. If you would like to get notified on GHA Action version bumps, go ahead and tune your _Custom Notifications_ for the Actions you use.

<img width="299" alt="Screenshot 2022-08-25 at 22 57 05" src="https://user-images.githubusercontent.com/6978377/186767692-e3d0e0f5-ac82-41a0-a511-17271332ef84.png">

---

Finally, I already stated in comment https://github.com/madminer-tool/madminer/pull/509#discussion_r954719603 that I am happy to be responsible for GHA Actions major version bumps until a new maintainer is "officially" appointed. There is no need to revisit this topic in the near future.

**Comment by matthewfeickert** [comment]
Okay, SGTM.

> As a last point: Dependabot should not be used as a _notification system_. If you would like to get notified on GHA Action version bumps, go ahead and tune your _Custom Notifications_ for the Actions you use.

Why do you say this though? This seems like a matter of personal choice. Am I missing a technical aspect?
