### ISSUE TITLE
Use gh-action-pypi-publish v1.7.0+ APIs

### ISSUE THREAD

**Issue by matthewfeickert** [madminer-tool/madminer#538]
In `pypa/gh-action-pypi-publish` `v1.7.0` inputs were changed to use kebab-case. Update to all inputs that were previously snake_case to use the new input format.
   - c.f. https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.7.0

**Comment by Sinclert** [comment]
Hey Matthew, I believe I did that already when merging the _Bump pypi-publish from 1.6.4 to 1.7.1_ [PR](https://github.com/madminer-tool/madminer/pull/534).

Let me know if you find any other occurrences. Will close this otherwise.

**Comment by matthewfeickert** [comment]
Yup. I had done a `grep -r` through my GitHub last night when I realized this and I guess I had an old version of the source code locally. Thanks for taking care of this. :+1:
